version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/node/app           # Mount current directory to /home/node/app in the container
      - node_modules:/home/node/app/node_modules  # Mount a named volume for node_modules to avoid conflicts
    working_dir: /home/node/app    # Set the working directory inside the container
    command: sh -c "yarn install && yarn dev"  # Run yarn install and then start the application
    depends_on:
      - mongo                       # Wait for the mongo service to be ready
    environment:
      DATABASE_URI: ${MONGO_URI}   # Environment variable for MongoDB URI
      PORT: ${PORT}
      NODE_ENV: development        # Set the Node environment to development
      PAYLOAD_SECRET: ${PAYLOAD_SECRET} 

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'               # Expose MongoDB's default port
    command:
      - --storageEngine=wiredTiger  # Specify storage engine (optional, can be omitted)
    volumes:
      - data:/data/db               # Use named volume for MongoDB data persistence
    logging:
      driver: none                  # Disable logging (optional)

volumes:
  data:                           # Define named volume for MongoDB data
  node_modules:                   # Define named volume for node_modules